name: Nodes.js CI

on: 
  push:
    branche:
      -main
  pull_request: 
    branche:
      -main

jobs:
  build:

    runs-on: ubuntu-lastet

    strategy:
      matrix:
        node-version: [20.x]
    
    step:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: start application
      run: npm start
